spring:
  application:
    name: mymall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: xxxxxxxxxxx
      secret-key: xxxxxxxxxxxx
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: bucket-name
    
server:
  port: 30000
  
  