spring:
  application:
    name: mymall-product
#  jpa:
#    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mymall_pms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Berlin
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
      
#    alicloud:
#      access-key: xxxxxxxxxxx
#      secret-key: xxxxxxxxxxxx
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
        
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000

logging:
  level:
    '[de.killbuqs.mall]': debug
    
    
    