spring:
  application:
    name: mymall-order
#  jpa:
#    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mymall_oms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 #采样值介于0和1之间，1表示全部采集
#      
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment(${server.port})
#    prefer-ip-address: true
      
      
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characerEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
    
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities 
