spring:
  application:
    name: mymall-search
#  jpa:
#    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

server:
  port: 12000   